### ISSUE TITLE
Overriding drawRect & memory

### ISSUE THREAD

**Issue by mrjjwright** [twitter-archive/twui#82]
Is there a reason that overriding drawRect with an empty implementation in an otherwise blank TUIView increases memory usage substantially?  This is probably a total newb question and has to do with the way CALayer handles content but I am totally seeing a 40 meg difference in memory when I add a few hundred TUIViews to a scroll view that do and don't override drawRect, even with an empty implementation?

I might remove this question here in a little bit as as I do some further testing.   Sorry to waste anybody's time but if somebody has a short answer that would be great.

**Comment by joshaber** [comment]
Take a look in `-[TUIView displayLayer:]`. If you don't implement `-drawRect:` then the view doesn't have to create a backing store. That saves time and memory.

Also note that if your view just needs a background color and nothing else, it's much more efficient to implement that by setting the `backgroundColor` property instead of implementing `-drawRect:` and filling manually. That's because `CALayer` has a built-in fast path for drawing a filled view that also avoids the need to create a backing store.

**Comment by joshaber** [comment]
(And if you come from UIKit land, the same is true there. UIView only creates a backing store if your subclass implements `-drawRect:`.)

**Comment by mrjjwright** [comment]
Oh yes, I read about this in the comments of the Chameleon UIView implementation and how it handles `displayLayer` and `displayLayer:inContect`.  BigZaphod notes that the basic machinery is as follows:

```
// Here's how CALayer appears to work:
// 1- something call's the layer's -display method.
// 2- arrive in CALayer's display: method.
// 2a-  if delegate implements displayLayer:, call that.
// 2b-  if delegate doesn't implement displayLayer:, CALayer creates a buffer and a context and passes that to drawInContext:
// 3- arrive in CALayer's drawInContext: method.
// 3a-  if delegate implements drawLayer:inContext:, call that and pass it the context.
// 3b-  otherwise, does nothing
```

Thanks Josh, this is very helpful to understand when creating simple container views!
