### ISSUE TITLE
TUINSView Drawing Problems

### ISSUE THREAD

**Issue by stoneros** [twitter-archive/twui#84]
hi,guys ,I'm trying to make a TUINSView's rootview transparent , but when I do that it look like I have drawing problem when set TUINSView->rootView's background as a [TUIColor clearColor].
It's look like ![This](http://iosnerd.com/TUINSView.png)
Did I doing Something wrong with this?

**Comment by kelan** [comment]
I just was working on this same issue.  The trick is that you need the TUINSView to be set as non-opaque, so that the view system knows to redraw the views underneath it. 

You can do this by calling -[TUINSView ab_setIsOpaque:NO].  However, that method is marked as deprecated (with a comment that says "don't use this"), so it might throw a warning/error during your build.  I'm not sure if there is another recommended way to set that view as non-opaque (I'd love to hear about it if there is), so I just temporarily solved that by removing the **attribute** in TUINSView.h in my local copy.

**Comment by stoneros** [comment]
thanks, That's work for me :)
