### ISSUE TITLE
How to make horizontal TUITableView?

### ISSUE THREAD

**Issue by philchia** [twitter-archive/twui#89]
When i add
self.tableView.transform = CGAffineTransformMakeRotation(M_PI \* 0.5);
the tableview just scroll left and right when i scroll up and down,how to fix this?
Please help?

**Comment by mrjjwright** [comment]
I have a TUITableView replacement I am working on called TUILayout that supports horizontal scrolling and animated updates ala UITableView.  See it at: https://github.com/mrjjwright/TUILayout.  

Alternatively, if you are up for it, you can make TUITableView scroll horizontally by replacing calculation lines code to calculate with x and width instead of y and height.  I got that working in about 30 minutes.  You will also need to fudge with TUIScrollView just a bit to get scrolling to work.  See TUIScrollView in TUILayout if you are interested.

**Comment by avaidyam** [comment]
What other classes did you modify to get TUILayout working? And why TUILayout as the name? That reminds me of Layout Managers a la Java's FlowLayout, etc etc.
